config/routes.rb
Passwordbucket::Application.routes.draw do

  resources :users, :only => [:new, :create, :show] do
    resources :credentials, :except => [:index]
  end
  
  resources :sessions, :only => [:new, :create, :destroy]

  match '/signup',      :to => 'users#new'
  match '/signin',      :to => 'sessions#new'
  match '/signout',     :to => 'sessions#destroy'
  
  match '/home',        :to => 'pages#home'
  match '/about',       :to => 'pages#about'
  match '/help',        :to => 'pages#help'
  match '/terms',       :to => 'pages#terms'
  match '/javascript_required',       :to => 'pages#javascript_required'
  
  match '/:user_id/destroy/:id',   :to => 'credentials#destroy'

  root :to => "pages#home"

end

app/models/credential.rb
class Credential < ActiveRecord::Base
  belongs_to :user
  
  attr_accessor :password, :service_password

  default_scope :order => 'credentials.created_at'
    
  validates :service, :presence => true, :length => { :maximum => 50 }
  validates :username, :presence => true, :length => { :maximum => 50 }
  validates :user_id, :presence => true
  validates :password, :presence     => true, :length => { :within => 6..40 }
                        
  validate :user_authentication

  private

  def user_authentication
    user = User.find(self.user_id)
    unless User.authenticate(user.username, self.password)
      errors.add(:password, "Your loboto.me password is incorrect.")
    end
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :credentials, :dependent => :destroy
  
  attr_accessor :password
  
  attr_accessible :username, :password, :password_confirmation
  before_save :encrypt_password
  
  validates :username, :presence => true, 
                       :uniqueness => { :case_sensitive => false },
                       :length  => { :within => 4..50 }, 
                       :format   => { :with => /\A[a-zA-Z\d]{4,}\z/i }                      

  validates :password, :presence     => true,
                       :confirmation => true,
                       :length       => { :within => 6..40 }
  
  
  def has_password?(submitted_password)
    hashed_password == encrypt(submitted_password)
  end

  def self.authenticate(username, submitted_password)
    user = find_by_username(username)
    return nil  if user.nil?
    return user if user.has_password?(submitted_password)
  end

  def self.authenticate_with_salt(id, cookie_salt)
    user = find_by_id(id)
    (user && user.salt == cookie_salt) ? user : nil
  end
  

  private

  def encrypt_password
    self.salt = make_salt if new_record?
    self.hashed_password = encrypt(password)
  end

  def encrypt(string)
    secure_hash("#{salt}--#{string}")
  end

  def make_salt
    secure_hash("#{Time.now.utc}--#{password}")
  end

  def secure_hash(string)
    Digest::MD5.hexdigest(string)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper
  
  before_filter :secure_domain_redirect, :except => ['session_expiry', 'update_activity_time']
  
  def secure_domain_redirect
    if request.url[0..4] == 'http:'
      redirect_to "https://lobotome.heroku.com#{request.env['PATH_INFO']}", :status => 301
    end
  end

  # This method checks if the user has been idle for more than 5 minutes, and if so, signs the user out.
  
  def session_expiry
    expiration = session[:expires_at]
    if (expiration == nil) || ((expiration - Time.now).to_i <= 0)
      sign_out
      reset_session
      flash[:error] = 'Your session has expired. Please sign in.'
      redirect_to signin_url
    end
  end

  # This method updates the current user's session to expire 5 minutes from now. 
  # It is called after every user action (except sign out) to tell the system that the user is actively using the application.

  def update_activity_time
    session[:expires_at] = 5.minutes.from_now
  end
  
  # The following basically removes the default validation error css form executing
  
  ActionView::Base.field_error_proc = Proc.new do |html_tag, instance|
    error_class = "fieldError"
    if html_tag =~ /<(input|textarea|select)[^>]+class=/
      style_attribute = html_tag =~ /class=['"]/
      html_tag.insert(style_attribute + 7, "#{error_class} ")
    elsif html_tag =~ /<(input|textarea|select)/
      first_whitespace = html_tag =~ /\s/
      html_tag[first_whitespace] = " class='#{error_class}' "
    end
    html_tag
  end

end

app/controllers/credentials_controller.rb
class CredentialsController < ApplicationController
  before_filter :authenticate
  before_filter :correct_user
  before_filter :session_expiry
  before_filter :update_activity_time
  
  # Standard REST actions
  
  def show
    @credential = Credential.find(params[:id])
  end

  def new
    @title = "New Credentials"
    @credential = Credential.new
  end

  def create
    @credential  = current_user.credentials.build(params[:credential]) 
    if @credential.save
      flash[:success] = "Credentials created!"
      redirect_to current_user
    else
      flash.now[:error] = "Your loboto.me password is incorrect."
      render 'new'
    end
  end

  def destroy
    @credential = Credential.find(params[:id])
    @credential.destroy
    redirect_to @user
  end
  
  private

    # This method makes sure the current user is the owner of the page being viewed.
    
    def correct_user
      @user = User.find(params[:user_id])
      redirect_to(root_path) unless current_user?(@user)
    end
    
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
  # These are all static pages, with the specified titles.
  
  def home
  end

  def about
    @title = "About"
  end

  def help
    @title = "Help"
  end

  def terms
    @title = "Terms"
  end

  def javascript_required
    @title = "Javascript Required"
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  # Standard REST actions

  def new
    @title = "Sign in"
  end

  def create
    user = User.authenticate(params[:session][:username], params[:session][:password])
    if user.nil?
      flash.now[:error] = "Invalid email/password combination."
      @title = "Sign in"
      render 'new'
    else
      sign_in user
      update_activity_time
      redirect_to user
    end
  end

  def destroy
    sign_out
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :session_expiry, :only => [:show]
  before_filter :update_activity_time, :only => [:show, :create]
  before_filter :authenticate, :only => [:show]
  before_filter :correct_user, :only => [:show]
  
  def new
    @title = "Sign up"
    @user = User.new
  end

  def show
    @credentials = @user.credentials
    @title = @user.username
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      sign_in @user
      flash[:success] = "Welcome to loboto.me!"
      redirect_to @user
    else
      if @user.errors.any?
        flash.now[:error] = @user.errors.full_messages.first
      end
      @title = "Sign up"
      render 'new'
    end
  end
  
  private
  
    def authenticate
      deny_access unless signed_in?
    end

    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_path) unless current_user?(@user)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper

  # Return a title on a per-page basis.
  
  def title
    base_title = "loboto.me"
    if @title.nil?
      base_title
    else
      "#{base_title} | #{@title}"
    end
  end

end

app/helpers/credentials_helper.rb
module CredentialsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def sign_in(user)
    cookies.permanent.signed[:remember_token] = [user.id, user.salt]
    current_user = user
  end

  def sign_out
    cookies.delete(:remember_token)
    self.current_user = nil
  end

  def current_user=(user)
    @current_user = user
  end
  
  def current_user
    @current_user ||= user_from_remember_token
  end
 
  def signed_in?
    !current_user.nil?
  end

  def current_user?(user)
    user == current_user
  end

  def authenticate
    deny_access unless signed_in?
  end

  def deny_access
    redirect_to signin_path, :notice => "Please sign in."
  end


  private

    def user_from_remember_token
      User.authenticate_with_salt(*remember_token)
    end

    def remember_token
      cookies.signed[:remember_token] || [nil, nil]
    end
  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/credentials/_decrypt.html.erb
<script>
  $(document).ready(function() {
		$("#destroyLink").click(function() {
			return confirm("Are you sure?");
		});
	});
	function decrypt() {
		$('<div id="passwordRequest"><a href="#" class="closeButton">x</a><br /><br />&nbsp;&nbsp;Please enter your loboto.me password <br /><br /> <input id="system_password" name="system_password" class="textField" size="30" type="password" /><br /><br /> <div id="submitDecryptPassword" class="uiButton smallButton"> <a id="submitDecryptPasswordLink" href="#">Submit</a></div></div>').appendTo('body');
		
		$("body").css("overflow", "hidden");
		
		var winW = $(window).width();
		var winY = $(window).height();
		
		// This makes the pasword request div appear in the center of the screen:
		$("#passwordRequest").css('left', winW/2-$("#passwordRequest").width()/2);
		$("#passwordRequest").css('top', winY/2-$("#passwordRequest").height()/2);
		$("#mask").addClass("maskShow").fadeIn("slow");
		$("#passwordRequest").fadeIn("slow");
		
		// This makes the mask and password request div become hidden when the user clicks on the darkened background:
		$("#mask").click(function() {
			$("#mask").hide();
			$("#passwordRequest").hide();
			$("body").css("overflow", "auto");
		});
		
		// This describes the small round x button in the top right corner of the password request div:
		$(".closeButton").click(function() {
			$("#mask").hide();
			$("#passwordRequest").hide();
			$("body").css("overflow", "auto");
		});
		
		$('#submitDecryptPasswordLink').click(function() {
			var submitted_password = $('#system_password').val();
			var salt = $("#salt").val();
			var key = calcMD5(salt+"--"+submitted_password);
			
			var crypted_password = $("#crypted").val();
			var decrypted_password = "";
			try
			  {
			    decrypted_password = GibberishAES.dec(crypted_password, key);
					$("#mask").hide();
					$("#passwordRequest").hide();
					$("#decrypt").html('<span style="font-size:20px;">Your password is: </span>'+decrypted_password);
			  }
			catch(err)
			  {
				// An error is thrown if the password provided is not correct.
				
			    $("#system_password").css('background', "#ff6c6c");
			    $("#system_password").focus(function() {
					  $("#system_password").css('background', "#fffa79");
					  $("#system_password").val("");
					});
			  }
		});
	}	
</script>

app/views/credentials/_encrypt.html.erb
<script>
	function encrypt() {
		var user_password = $('#credential_password').val();
		var credential_password = $('#credential_service_password').val();		
	  var now = new Date();
	  var salt = calcMD5(now.getTime()+"--"+user_password);
		var key = calcMD5(salt+"--"+user_password);
		var encrypted_credential_password = GibberishAES.enc(credential_password, key);
		$('#credential_crypted_password').val(encrypted_credential_password);
		$('#credential_salt').val(salt);
    return true;
	}	
</script>

app/views/credentials/new.html.erb
<h1>New credential</h1>

<div id= "centralizedForm">
	<%= form_for [@user, @credential], :html=> {:onSubmit => "return encrypt();"} do |f| %>
  
		<div class="textFieldLabel">
			<%= f.label :service %>
		</div>
	
		<%= f.text_field :service, :class=>"textField" %><br />
  	
		<div class="textFieldLabel">
			<%= f.label :username %>
		</div>
		
		<%= f.text_field :username, :class=>"textField" %><br />
		
  	<div class="textFieldLabel">
			<%= f.label :service_password, "Password to Encrypt" %>
		</div>
		
		<%= f.password_field :service_password, :class=>"textField" %><br />
		
  	<div class="textFieldLabel"><%= f.label :password, "loboto.me Password" %></div><%= f.password_field :password, :class=>"textField" %><br />
  	
		<%= f.hidden_field :salt %>
  	
		<%= f.hidden_field :crypted_password %>
  
		<div  class="textFieldLabel">
    	<%= f.submit "Add Credential", :class=>"btn", :onmouseover=>"this.className='btn btnhov'", :onmouseout=>"this.className='btn'" %>
  	</div>
	<% end %>
</div>

<div class="credsTableRowCol">
	<%= link_to 'Back', @user %>
</div>

<%= render 'credentials/encrypt' %>

app/views/credentials/show.html.erb
<h1>Credential</h1>

<div style="text-align:left;padding-left:10px">
	<p>
	  <span style="font-size:20px;">Service:</span>
	  <%=h @credential.service %>
	</p>

	<p>
	  <span style="font-size:20px;">Username:</span>
	  <%=h @credential.username %>
	</p>

	<div id="decrypt">
		<div class="uiButton smallButton blueButton">
			<%=link_to "Decrypt Password", "#", :onClick=>"decrypt();" %>
		</div>
	</div>	
	<div class="uiButton smallButton redButton">
		<%= link_to 'Destroy Credential', "/#{@user.id}/destroy/#{@credential.id}", :id=>"destroyLink"%>
	</div>
</div>

<div class="credsTableRowCol">
	<%= link_to 'Back', @user %>
</div>

<input id="crypted" type="hidden" value="<%=@credential.crypted_password%>">
<input id="salt" type="hidden" value="<%=@credential.salt%>">

<%= render 'credentials/decrypt' %>

app/views/layouts/_analytics.html.erb
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-17159400-4']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>

app/views/layouts/_footer.html.erb
<div id="footerContainer">
	<footer>
	  <nav>
	    <ul>
				<li><span style="color:#fff;">© 2010 loboto.me</span></li>
	      <li><%= link_to "About", about_url %></li>
	      <li><%= mail_to 'andresbonilla@gmail.com', 'Contact' %></li>
	      <li><%= link_to "Help", help_url %></li>
	      <li><%= link_to "Terms", terms_url %></li>
	      <li><%= link_to "Source", "http://github.com/andresbonilla/loboto.me" %></li>
	    </ul>
	  </nav>
	</footer>
</div>

app/views/layouts/_head.html.erb
<head>
	<% unless @title == 'Javascript Required' %>
		<noscript>
			<meta HTTP-EQUIV="REFRESH" content="0; url=<%=javascript_required_url-%>"> 
		</noscript>
	<% end %>
  <title><%= title %></title>
  <%= csrf_meta_tag %>
  <%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
  <%= stylesheet_link_tag 'blueprint/print',  :media => 'print' %>
  <%= stylesheet_link_tag 'custom', :media => 'screen' %>
  <%= javascript_include_tag 'gibberish-aes.min.js' %>
  <%= javascript_include_tag 'jquery-1.4.2.min.js' %>
  <%= javascript_include_tag 'md5.js' %>
  <%= render 'layouts/analytics' %>
</head>

app/views/layouts/_header.html.erb
<header>
  <%= link_to root_url do %>	
		<%= image_tag "logo.png" %>
	<% end %>
  <nav>
    <ul>
      <li><%= link_to "Home", root_path %></li>
			<% if signed_in? %>
			  <li><%= link_to "Profile", current_user %></li>
			<% end %>
      <li><%= link_to "Help", help_url %></li>
      <% if signed_in? %>
      <li><%= link_to "Sign out", signout_path, :method => :delete %></li>
      <% else %>
      <li><%= link_to "Sign in", signin_path %></li>
      <% end %>
    </ul>
  </nav>
<div style="clear:both"></div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<%= render 'layouts/head' %>
  <body>
	<div id="mask" class="mask"></div>
    <div class="container">
      <%= render 'layouts/header' %>
      <section id="mainContent">
				<% flash.each do |key, value| %>
				  <div class="flash <%= key %>"><%= value %></div>
				<% end %>
				<%= yield %>
      </section>
			<%= render 'layouts/footer' %>
    </div>
</body>
</html>

app/views/pages/about.html.erb
<h1>About</h1>
<div class="staticText">loboto.me is a credential repository that allows users to store all of their usernames and passwords securely in one place. All passwords are only stored in encrypted form, so even we cannot read them. There is no recovering forgotten passwords, since your loboto.me account password is the crucial part of the decryption key for your stored credential passwords.</div>

app/views/pages/help.html.erb
<h1>Help</h1>
<div class="staticText">
	<div class="question">How do I get started?</div>
	<div>&bull;&nbsp;To use loboto.me you must create an account <%=link_to "here",signup_url -%>.</div>
</div>
<br />
<div class="staticText">
	<div class="question">How do I add credentials?</div>
	<div>&bull;&nbsp;To add credentials, first sign in <%=link_to "here",signin_url -%>.</div>
	<div>&bull;&nbsp;After signing in, click on the green button that reads 'New Credential'.</div>
	<div>&bull;&nbsp;Fill in the form with your new credential's information and click on the green button that reads 'Add Credential'.</div>
</div>
<br />
<div class="staticText">
	<div class="question">How do I edit credentials?</div>
	<div>&bull;&nbsp;Credentials cannot be edited. Delete credentials you no longer want and create new ones with the correct values.</div>
</div>
<br />
<div class="staticText">
	<div class="question">How do I delete credentials?</div>
	<div>&bull;&nbsp;Go to the credential's page and click on the red button that reads 'Delete Credential'.</div>
</div>
<br />
<div class="staticText">
	<div class="question">I forgot my loboto.me password. How can I recover it?</div>
	<div>&bull;&nbsp;There is nothing you can do to recover access yo your account if you forgot your loboto.me password. Only encrypted versions of your passwords are stored.</div>
</div>
<br />
<div class="staticText">
	<div class="question">What if I have more questions?</div>
		<div>&bull;&nbsp;Please send any questions through the contact link. We will do our best to answer them promptly.</div>	
</div>

app/views/pages/home.html.erb
<div class="staticText">
	<div class="bigText">
		<%=link_to "1.Sign up", signup_url -%><br />
		2.Submit<br />
		3.Encrypt
	</div>
	<br />
	<div id="slogan"><span id="sloganTitle">loboto.me</span>: smart and secure password storage.</div>
</div>

app/views/pages/javascript_required.html.erb
<h1>Javascript Required</h1>
<div class="staticText">You must have Javascript enabled on your browser to use loboto.me</div>

app/views/pages/terms.html.erb
<h1>Terms</h1>
<div class="staticText">
	By using loboto.me, you signify that you have read, understand and agree to be bound by these Terms and conditions.
	
	loboto.me is concerned about the safety and privacy of all its Users, especially children. Therefore, children under the age of 13 are not permitted to use loboto.me. 
		
	We reserve the right to ban any individual uploader or website domain from using our servies for any reason. 

	We cannot be held liable for any damages. All data, messages, comments, text, or other materials ("Content"), are the sole responsibility of the person from whom such Content originated. You, and not loboto.me, are entirely responsible for all Content that you upload, post, email, transmit or otherwise make available through loboto.me. loboto.me does not control the Content posted and does not guarantee the accuracy or integrity of such Content. 

	loboto.me will not be liable in any way for any Content, including, but not limited to, any errors or omissions in any Content. loboto.me will not be liable for any loss or damage of any kind incurred as a result of the use of any Content posted, emailed, transmitted or otherwise made available on loboto.me. loboto.me assumes no responsibility for the timeliness, deletion, miss-delivery or failure to store any User content, communication or personal settings. 

	You agree to indemnify and hold loboto.me, its officers and employees exempt from any claim or demand, including reasonable attorneys' fees, made by any third party due to or arising out of Content you submit, transmit, post or otherwise make available through loboto.me. 

	Choice of Law and Forum 

	The Terms of Service and the relationship between you and loboto.me shall be governed by the laws of the Commonwealth of Puerto Rico without regard to its conflict of law provisions. You and loboto.me agree to submit to the personal and exclusive jurisdiction of the courts located within San Juan, Puerto Rico. 

	Statute of Limitations 

	You agree that regardless of any statute or law to the contrary, any claim or cause of action arising out of or related to use of the Service or the Terms of Service must be filed within one (1) year after such claim or cause of action arose or be forever barred. 

	Improper Use of Data 

	Data mining, "scrapping", and/or unauthorized crawling of loboto.me is prohibited unless explicit permission is given. Using any data from loboto.me (including data from images and/or users) that is not available through authorized channels is also prohibitied unless explicit permission is given. 
<br /><br />
<p>
	Mailing Address:<br />
	<br />
	Attention: Andrés Bonilla<br />
	loboto.me<br />
	Villas del Rio calle 16, apt. c17<br />
	Bayamón, Puerto Rico 00959<br />
</p>
</div>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<div id= "centralizedForm">
	
	<%= form_for(@user) do |f| %>
	 
		<div style="margin-bottom:10px;">
			
			<div class="textFieldLabel">
				<%= f.label :username %>
			</div>
			
			<%= f.text_field :username, :class=>"textField" %><br />
   
		  <div class="textFieldLabel">
				<%= f.label :password %>
			</div>
			
			<%= f.password_field :password, :class=>"textField" %><br />
  
		  <div class="textFieldLabel">
				<%= f.label :password_confirmation, "Confirmation" %>
			</div>
			
			<%= f.password_field :password_confirmation, :class=>"textField" %><br />
			
			<div class="reminder">
				*Remember your password. We only store an encrypted version of it, so we couldn't remind you even if we wanted to. If you forget it, you will lose access to your account.
			</div><br />
	  
		</div> 
		<div  class="textFieldLabel">
	    <%= f.submit "Sign Up", :class=>"btn", :onmouseover=>"this.className='btn btnhov'", :onmouseout=>"this.className='btn'" %>
	  </div> 
	<% end %>
</div>

app/views/users/show.html.erb
<h1><%=h @user.username %></h1>

	<div class="credsTableWrapper">
		<% if @credentials.size == 0 %>
			<div id="noCredentialsYet">You have not added any credentials yet.</div>
		<% else %>
		<div class="credsTableHeader">
		
			<div class="credsTableHeaderCol">Service</div>
			
			<div class="credsTableHeaderCol">Username</div>
			
			<div style="clear:both;"></div>
		
		</div>
		<% end %>
		<div class="credsTableContent">
		
			<% @credentials.each do |credential| %>
			
			<div class="credsTableRowWrapper">
			
				<div class="credsTableRowCol"><%=h credential.service %></div>
			
				<div class="credsTableRowCol"><%=h credential.username %></div>
			
				<div class="credsTableRowCol" align="right"><%= link_to 'View', user_credential_path(@user, credential) %></div>
			
				<div style="clear:both;"></div>
			
			</div>
			
			<% end %>
				<div class="credsTableRowCol newCredentialButton">
					<div class="uiButton"><%= link_to 'New Credential', new_user_credential_path(@user) %></div>
				</div>
		</div>
		
		<div style="clear:both;"></div>
		
	</div>